title: Sarah Blunt, PhD
logo: /assets/img/headshot.png
description: NSF A&A Postdoc Fellow | UC Santa Cruz \\ sarah <DOT> sblunt <DOT> 3 <AT> gmail <DOT> com
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
